# Basic
title: 学习共同体联合会
subtitle: 求真、求实、求证
welcome_message: 我们在一起，就是学习共同体! 
description: 秉持佐藤学先生学习共同体之哲学理念，展示两岸三地理论研究与实践探索之材料。
creator: <a href="http://www.slc.education">@ 学习共同体联合会</a>

url: "http://www.slc.education/blog/#blog"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 主页,     in_site: false,  description: 联合会主页,    url: 'http://slc.education'}
    - {title: 目录,        in_site: true,  description: 博客目录,               url: '/timeline'}
    - {title: 关于,        in_site: true,  description: 关于作者 GcsSloop,       url: '/info/about'}
    


gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    #disqus: GcsSloop
    duoshuo:Mettadann
# Social
social:
    weibo: slc-china
    rss: /feed.xml
    mail: contact@slc.education
    copyright: http://choosealicense.online

# Google Analytics
ga:
    id: UA-79014677-2
    host: www.slc.education
